enabled: true

changed_paths:
  maximum: 1000
  outcome: error

remote_files: []

auto: false

commit_template: |
  Restyled by ${restyler.name}
pull_requests: true

comments: false

statuses:
  differences: true
  no_differences: true
  error: true

request_review: author

labels: []

ignore_labels:
  - restyled-ignore

restylers_version: stable

restylers:
  - isort

  - yapf:
      arguments: ["--style", "google"]

  - name: prettier
    include: ["**/*.md"]

  - name: prettier
    include: ["**/*.yml"]
