name: Feature Proposal
description: Create a feature request for Anjani
title: "[FEAT] "
labels: ["type: feature", "feature: addition", "status: triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a feature! Please fill out this form as completely as possible.
        Feature request will be converted to the [Github Discussions (Ideas 💡)](https://github.com/userbotindo/Anjani/discussions/categories/ideas)
        and will be mentioned on a new issue if the feature is accepted.
  - type: textarea
    attributes:
      label: Describe the feature you'd like to request
      description: A clear and concise description of what you want, what your use case is and what problem are you trying to solve.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
