// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID          int32
	ChatID      int32
	Title       string
	Type        string
	IsForum     bool
	IsBotMember bool
	Hash        *string
	LastUpdate  pgtype.Timestamp
}

type ChatMember struct {
	ChatID int32
	UserID int32
}

type ChatSetting struct {
	ChatID               int32
	Language             *string
	Rules                *string
	ActionTopic          *int32
	SpamDetectionSetting *bool
	WarnLimit            *int32
	Reporting            *bool
	GlobalBan            *bool
	Lockings             []string
}

type ChatWarning struct {
	ChatID  int32
	UserID  int32
	Count   *int32
	Reasons []string
}

type Federation struct {
	FederationID string
	Name         string
	OwnerID      int32
	LogChatID    *int32
}

type FederationAdmin struct {
	FederationID string
	UserID       int32
}

type FederationBan struct {
	FederationID string
	UserID       int32
}

type FederationChat struct {
	FederationID string
	ChatID       int32
}

type FederationSubscriber struct {
	FederationID           string
	FederationSubscriberID string
}

type Filter struct {
	FilterID string
	ChatID   *int32
	Keyword  string
	Content  *string
	Type     *int32
}

type FilterButton struct {
	FilterID   *string
	Text       string
	Url        string
	IsSameLine *bool
}

type Greeting struct {
	GreetingID     string
	ChatID         *int32
	CleanService   *bool
	WelcomeMessage *string
	GoodbyeMessage *string
	File           *string
	PrevWelcomeID  *int32
	PrevGoodbyeID  *int32
	ShouldWelcome  *bool
	ShouldGoodbye  *bool
	Type           *int32
}

type GreetingButton struct {
	GreetingID *string
	Text       string
	Url        string
	IsSameLine *bool
}

type Note struct {
	NoteID     string
	ChatID     *int32
	Name       string
	Content    *string
	File       *string
	HasButtons *bool
	NoteType   *int32
}

type NoteButton struct {
	NoteID     *string
	Name       string
	Url        string
	IsSameLine *bool
}

type User struct {
	UserID     int32
	Username   string
	Hash       string
	IsStarted  *bool
	Reputation *float64
	LastSeen   pgtype.Timestamp
}

type UserSetting struct {
	UserID    int32
	Rank      *string
	Language  *string
	Reporting *bool
}
