// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID          int32
	ChatID      int64
	Title       string
	Type        string
	IsForum     bool
	IsBotMember bool
	Hash        *string
	LastUpdate  pgtype.Timestamp
}

type ChatMember struct {
	ChatID    int64
	UserID    int64
	WarningID *int32
}

type ChatSetting struct {
	ChatID               int64
	Language             *string
	Rules                *string
	ActionTopic          *int32
	SpamDetectionSetting *bool
	WarnLimit            *int32
	Reporting            *bool
	GlobalBan            *bool
	Lockings             []string
}

type ChatWarning struct {
	WarningID int32
	Count     *int32
	Reasons   []string
}

type Federation struct {
	FederationID string
	Name         string
	OwnerID      int32
	LogChatID    *int64
}

type FederationAdmin struct {
	FederationID string
	UserID       int64
}

type FederationBan struct {
	FederationID string
	UserID       int64
}

type FederationChat struct {
	FederationID string
	ChatID       int64
}

type FederationSubscriber struct {
	FederationID           string
	FederationSubscriberID string
}

type Filter struct {
	ID      int32
	ChatID  *int64
	Keyword string
	Content *string
	Type    *int32
}

type FilterButton struct {
	FilterID   *int32
	Text       string
	Url        string
	IsSameLine *bool
}

type Greeting struct {
	ID             int32
	ChatID         *int64
	CleanService   *bool
	WelcomeMessage *string
	GoodbyeMessage *string
	File           *string
	PrevWelcomeID  *int64
	PrevGoodbyeID  *int64
	ShouldWelcome  *bool
	ShouldGoodbye  *bool
	Type           *int32
}

type GreetingButton struct {
	GreetingID *int32
	Text       string
	Url        string
	IsSameLine *bool
}

type Note struct {
	ID         int32
	ChatID     *int64
	Name       string
	Content    *string
	File       *string
	HasButtons *bool
	NoteType   *int32
}

type NoteButton struct {
	NoteID     *int32
	Name       string
	Url        string
	IsSameLine *bool
}

type User struct {
	UserID     int64
	Username   string
	Hash       string
	IsStarted  *bool
	Reputation *float64
	LastSeen   pgtype.Timestamp
}

type UserSetting struct {
	UserID    int64
	Rank      *string
	Language  *string
	Reporting *bool
}
