// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"
)

const getUserById = `-- name: GetUserById :one
SELECT user_id, username, hash, is_started, reputation, last_seen FROM public.user WHERE user_id = $1
`

func (q *Queries) GetUserById(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Hash,
		&i.IsStarted,
		&i.Reputation,
		&i.LastSeen,
	)
	return i, err
}
